---
# YUM/RPM: .rpm or repo install
- name: Download 1Password CLI .rpm (YUM/RPM)
  ansible.builtin.get_url:
    url: "{{ op_cli_rpm_url }}"
    dest: "{{ op_cli_rpm_path }}"
    mode: '0644'
  when: op_cli_install_method is defined and op_cli_install_method == 'rpm'
  tags: [install]

- name: Install 1Password CLI .rpm (YUM/RPM)
  ansible.builtin.yum:
    name: "{{ op_cli_rpm_path }}"
    state: present
  become: true
  when: op_cli_install_method is defined and op_cli_install_method == 'rpm'
  tags: [install]

- name: Import 1Password GPG key (YUM/RPM)
  ansible.builtin.rpm_key:
    state: present
    key: "{{ op_rpm_key_url }}"
  become: true
  when: op_cli_install_method is not defined or op_cli_install_method != 'rpm'
  tags: [repo]

- name: Add 1Password YUM repo file (YUM/RPM)
  ansible.builtin.copy:
    dest: "{{ op_rpm_repo_file }}"
    content: |
      [1password]
      name=1Password Stable Channel
      baseurl={{ op_rpm_repo_url }}
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey={{ op_rpm_key_url }}
    mode: '0644'
  become: true
  when: op_cli_install_method is not defined or op_cli_install_method != 'rpm'
  tags: [repo]

- name: Install 1Password CLI (YUM/RPM)
  ansible.builtin.yum:
    name: 1password-cli
    state: present
  become: true
  when: op_cli_install_method is not defined or op_cli_install_method != 'rpm'
  tags: [install]

- name: Uninstall 1Password CLI (YUM/RPM)
  ansible.builtin.yum:
    name: 1password-cli
    state: absent
  become: true
  when: op_cli_absent | bool
  tags: [uninstall]

- name: Remove 1Password CLI .rpm file (if present)
  ansible.builtin.file:
    path: "{{ op_cli_rpm_path }}"
    state: absent
  when: op_cli_absent | bool
  tags: [uninstall]
